# YAML是一种直观的数据序列化格式，以数据为核心的，比传统的xml方式更加简洁。其扩展名可以使用.yml或者.yaml。
# 1.常用数据格式
#     语法：key: value
#     示例：name: zhangsan
#     注意：value之前有一个空格
# 2.配置对象或map数据
#     语法：
#         key:
#             key1: value1
#             key2: value2
#     或者
#        key: {key1: value1,key2: value2}
#     示例：
#     person:
#            name: zhangsan
#            age: 30
#            addr: beijing
#     或者
#     person: {name: zhangsan,age: 30,addr: beijing}
# 3.配置List,Set数据
#      语法：
#        key:
#             - value1
#             - value2
#       或者
#        key: [value1,value2]
#       示例：
#        city:
#          - beijing
#          - tianjin
#       或者
#         city: [beijing,tianjin]
# 4.集合中的元素是对象形式
#        student:
#            - name: zhangsan
#                 age: 19
#                 score: 100
#            - name: lisi
#                 age: 28
#                 score: 89
#            - name: wangwu
#                 age: 38
#                 score: 91
# 注意：value1与之前的 - 之间存在一个空格
mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: root123
  log_level: dev
logger:
  # level: warning
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2023-02-15"
  bei_an: 湘ICP备2021010654号-3
  title: 枫枫知道
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2663456523@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 枫枫知道
  job: 后端开发
  addr: 湖南长沙
  slogan: 枫枫知道
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
upload:
  size: 2
  path: uploads/file
qq:
  app_id: "101974593"
  key: xxx
  redirect: http://blog.fengfengzhidao.com/login?flag=qq
qi_niu:
  enable: true
  access_key: ZnP90V73cxgvRQSqfae19FnK6N3GMMSxB2-l_nBn
  secret_key: bD7SZh_at4kPNsL28scBGgEWCHbJNOnsR8zOVUAH
  bucket: sportphotos
  cdn: http://rtworch7c.hn-bkt.clouddn.com/
  zone: z2
  prefix: fengfeng
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: 2974771769@qq.com
  password: xxx
  default_from_email: 枫枫知道
  use_ssl: true
  user_tls: false
jwy:
  secret: xxxx
  expires: 20
  issuer: "1234"
redis:
  ip: 127.0.0.1
  port: 6379
  password:
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
